version: "3"
services:
  stocksdata:
    container_name: stocksdata
    build: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env

  postgres-database:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
    restart: always

  db-admin:
    image: dpage/pgadmin4:8.5
    tty: true
    ports:
      - 8081:80
    depends_on:
      - postgres-database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@user.com
      PGADMIN_DEFAULT_PASSWORD: qwezxcfgh1

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
