version: "3"
services:
  postgres-database:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
    restart: always

  db-admin:
    image: dpage/pgadmin4:8.5
    tty: true
    ports:
      - 8081:80
    depends_on:
      - postgres-database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@user.com
      PGADMIN_DEFAULT_PASSWORD: qwezxcfgh1
